name: Basic Tests
on:
  pull_request:
  push:
    branches:
    - release

jobs:
  testcases_check:
    name: testcases check
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: installbuild
      run: |
        docker build -t build-hsm ./firmware
        docker run --rm -v ./firmware:/hsm -v ./global.secrets:/secrets/global.secrets:ro -v ./build:/out -e HSM_PIN='123abc' -e PERMISSIONS='1234=R--:4321=RWC' build-hsm
    - name: flashstart
      run: |
        uvx ectf hw /dev/tty.usbmodemM43210051 erase
        uvx ectf hw /dev/tty.usbmodemM43210051 flash ./build/hsm.bin -n hsm
        uvx ectf hw /dev/tty.usbmodemM43210051 start
    - name: runtest
      run: python3 scripts/tests/test_main.py --port /dev/tty.usbmodemM43210051
